-- 관리자

SELECT
    *
FROM DBA_TABLESPACES;

DROP USER iouser CASCADE;


CREATE USER iouser IDENTIFIED BY iouser;

GRANT DBA TO iouser;

DROP TABLESPACE iolistDB INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS ;

-- Iolist를 위한 TableSpace 생성
CREATE TABLESPACE iolistDB DATAFILE 'C:/oraclexe/data/iolist.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER iouser IDENTIFIED BY iouser DEFAULT TABLESPACE iolistDB;

GRANT DBA TO iouser;

-- 오라클의 System 값
SELECT * FROM DBA_PROFILES;

-- 오라클에 새로 등록된 사용자의 Password 만료일자
-- 기본값이 LIMIT 에 담겨있는 180( 180일 ) 후에 접속이 불가능해 진다.
SELECT * FROM DBA_PROFILES WHERE resource_name = 'PASSWORD_LIFE_TIME';

-- 사용자의 Password 만료일자를 무제한으로 변경
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
