CREATE TABLESPACE iolistDB
DATAFILE 'c:/oraclexe/data/iolist.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE user iouser IDENTIFIED BY iouser
DEFAULT TABLESPACE iolistDB;
GRANT CREATE SESSION TO iouser;
GRANT DBA TO iouser;

DROP USER iouser CASCADE;

DROP TABLESPACE iolistDB
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;
